### ISSUE TITLE
用户空间的单节点内存不显示

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/OpenSCOW#1460]
### 发生了什么 | What happened

用户空间的单节点内存不显示
<img width="874" alt="image" src="https://github.com/user-attachments/assets/a4ab9309-4ba7-4995-b3b9-9e6be8bfde36">

* scontrol show node=nodename 的内存结果
```
   RealMemory=3932160 AllocMem=0 FreeMem=4119101 Sockets=4 Boards=1
```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Scheduler: slurm-22.05.11
- Docker: 24.0.9
- Docker-compose: 2.24.1
- SCOW cli: v1.5.2
- SCOW: v1.5.2
- Adapter: slurm-adapter v1.5.0
```

**Comment by piccaSun** [comment]
请问是否还有这个问题，如果还有请您确认slurm下 scontrol show partition=C96T4下的分区内存信息是否显式正常

**Comment by liu-shaobo** [comment]
是因为mem后面的值为T，所以显示有问题？
<img width="591" alt="image" src="https://github.com/user-attachments/assets/6a8eba91-e48d-4f47-88fe-c5817343ac7f">

**Comment by 283713406** [comment]
麻烦执行下这条命令 scontrol show node=node221 | grep  RealMemory=| awk '{print $1}' | awk -F'=' '{print $2}'

**Comment by liu-shaobo** [comment]
<img width="969" alt="image" src="https://github.com/user-attachments/assets/0e447920-bf2b-4079-80fc-9b75cc5f735a">

**Comment by 283713406** [comment]
适配器https://github.com/PKUHPC/scow-slurm-adapter是用最新的代码编译的吗？麻烦能否将日志级别调整为trace，然后看看日志里面GetClusterConfig:或者GetAvailablePartitions:字眼的日志？

**Comment by liu-shaobo** [comment]
适配器使用的1.5.0，日志级别调整为trace。
```
# 日志级别
log:
  level: "trace"
```
重启适配器后，级别还是info，这是什么原因？
```
{"level":"info","msg":"Received request GetClusterConfig: ","time":"2024-11-28T17:13:43+08:00"}
```

**Comment by piccaSun** [comment]
您好，在1.5.0版本中还没有增加trace级别日志的判断
如果您方便的话，烦请您更新适配器到 master ，更改日志等级为 trace 打印更详细的日志来帮助我们的判断

**Comment by 283713406** [comment]
@liu-shaobo 您可以根据适配器的fix-memory分支编译一个适配器，能解决该问题。https://github.com/PKUHPC/scow-slurm-adapter/tree/fix-memory

**Comment by liu-shaobo** [comment]
好的，我重新编译试试。

**Comment by 283713406** [comment]
@liu-shaobo 请问下这个问题得到解决了吗？

**Comment by 283713406** [comment]
@liu-shaobo 不好意思，fix-memory分支的代码优点问题，我又修改，如下
![image](https://github.com/user-attachments/assets/01cfcf32-7a10-4c82-ad39-8592652a6442)
再麻烦基于fix-memory分支重新编译一下，然后试下。多谢啦！

**Comment by liu-shaobo** [comment]
用fix-memory分支编译，在scow-1.5.2上测试，进入scow管理系统会出现500错误；

* services/config/config.go内容
<img width="753" alt="image" src="https://github.com/user-attachments/assets/adcc4567-37b9-4093-a6f1-6e1c578e1a13">

* slurm-adapter的trace日志
```
[2024-12-05 14:58:35] [info] [config.go:34 scow-slurm-adapter/services/config.(*ServerConfig).GetClusterConfig] Received request GetClusterConfig:
[2024-12-05 14:58:35] [error] [config.go:182 scow-slurm-adapter/services/config.(*ServerConfig).GetClusterConfig] GetClusterConfig failed: rpc error: code = Internal desc = convert memory error
```
* mis-server日志
```
mis-server-1  | > @scow/mis-server@1.5.2 serve
mis-server-1  | > node build/index.js
mis-server-1  |
mis-server-1  | {"level":30,"time":"2024-12-05T07:04:17.649Z","pid":18,"hostname":"a6d69092e87b","msg":"Hook is not configured."}
mis-server-1  | {"level":30,"time":"2024-12-05T07:04:17.883Z","pid":18,"hostname":"a6d69092e87b","version":{"tag":"v1.5.2","commit":"665f5316212c99f7d461736134c1744e1b38084b"},"msg":"@scow/mis-server: "}
mis-server-1  | {"level":30,"time":"2024-12-05T07:04:17.883Z","pid":18,"hostname":"a6d69092e87b","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","AUTH_URL":"","DB_PASSWORD":"must!chang3this"},"msg":"Loaded env config"}
mis-server-1  | {"level":30,"time":"2024-12-05T07:04:18.112Z","pid":18,"hostname":"a6d69092e87b","msg":"Checking if root can login to hpc01 by login node node196"}
mis-server-1  | {"level":30,"time":"2024-12-05T07:04:18.164Z","pid":18,"hostname":"a6d69092e87b","msg":"Root can login to hpc01 by login node node196"}
mis-server-1  | {"level":30,"time":"2024-12-05T07:04:18.189Z","pid":18,"hostname":"a6d69092e87b","plugin":"price","msg":"Default Price Map: {\"hpc01.C96T2.normal\":{\"id\":1,\"itemId\":\"1\",\"path\":[\"hpc01\",\"C96T2\",\"normal\"],\"description\":\"\",\"price\":\"0.1\",\"amount\":\"cpusAlloc\",\"createTime\":\"2024-12-05T01:30:02.378Z\"}}"}
mis-server-1  | {"level":30,"time":"2024-12-05T07:04:18.189Z","pid":18,"hostname":"a6d69092e87b","plugin":"price","msg":"Tenant specific prices {}"}
mis-server-1  | {"level":50,"time":"2024-12-05T07:04:18.240Z","pid":18,"hostname":"a6d69092e87b","plugin":"price","err":{"type":"Error","message":"13 INTERNAL: convert memory error","stack":"Error: 13 INTERNAL: convert memory error\n    at callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.6/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.6/node_modules/@grpc/grpc-js/build/src/client.js:193:76)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.6/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.6/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n    at /app/node_modules/.pnpm/@grpc+grpc-js@1.10.6/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.6/node_modules/@grpc/grpc-js/build/src/client.js:161:32)\n    at ServiceClientImpl.getClusterConfig (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.6/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n    at /app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.7_@grpc+grpc-js@1.10.6/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:18:13\n    at new Promise (<anonymous>)\n    at asyncClientCall (/app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.7_@grpc+grpc-js@1.10.6/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:15:12)\n    at /app/apps/mis-server/build/bl/PriceMap.js:49:117\n    at /app/apps/mis-server/build/plugins/clusters.js:84:24\n    at Array.map (<anonymous>)\n    at Object.callOnAll (/app/apps/mis-server/build/plugins/clusters.js:83:18)\n    at createPriceMap (/app/apps/mis-server/build/bl/PriceMap.js:49:39)","code":13,"details":"convert memory error","metadata":{"content-type":["application/grpc"],"grpc-status-details-bin":[{"type":"Buffer","data":[8,13,18,20,99,111,110,118,101,114,116,32,109,101,109,111,114,121,32,101,114,114,111,114,26,67,10,40,116,121,112,101,46,103,111,111,103,108,101,97,112,105,115,46,99,111,109,47,103,111,111,103,108,101,46,114,112,99,46,69,114,114,111,114,73,110,102,111,18,23,10,21,67,79,78,86,69,82,84,95,77,69,77,79,82,89,95,70,65,73,76,69,68]}]}},"msg":"Executing on hpc01 failed"}
mis-server-1  | {"level":50,"time":"2024-12-05T07:04:18.241Z","pid":18,"hostname":"a6d69092e87b","plugin":"price","msg":"Cluster ops fails at clusters [{\"cluster\":\"hpc01\",\"error\":{\"code\":13,\"details\":\"convert memory error\",\"metadata\":{\"content-type\":[\"application/grpc\"],\"grpc-status-details-bin\":[{\"type\":\"Buffer\",\"data\":[8,13,18,20,99,111,110,118,101,114,116,32,109,101,109,111,114,121,32,101,114,114,111,114,26,67,10,40,116,121,112,101,46,103,111,111,103,108,101,97,112,105,115,46,99,111,109,47,103,111,111,103,108,101,46,114,112,99,46,69,114,114,111,114,73,110,102,111,18,23,10,21,67,79,78,86,69,82,84,95,77,69,77,79,82,89,95,70,65,73,76,69,68]}]}}}]"}
mis-server-1  | /app/apps/mis-server/build/plugins/clusters.js:107
mis-server-1  |                 throw new tsgrpc_common_1.ServiceError({
mis-server-1  |                       ^
mis-server-1  |
mis-server-1  | ServiceError
mis-server-1  |     at Object.callOnAll (/app/apps/mis-server/build/plugins/clusters.js:107:23)
mis-server-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
mis-server-1  |     at async createPriceMap (/app/apps/mis-server/build/bl/PriceMap.js:49:19)
mis-server-1  |     at async /app/apps/mis-server/build/plugins/price.js:20:22
mis-server-1  |     at async Server.register (/app/node_modules/.pnpm/@ddadaal+tsgrpc-server@0.19.5_@grpc+grpc-js@1.10.6/node_modules/@ddadaal/tsgrpc-server/lib/server.js:117:9)
mis-server-1  |     at async createServer (/app/apps/mis-server/build/app.js:41:9)
mis-server-1  |     at async main (/app/apps/mis-server/build/index.js:19:20) {
mis-server-1  |   code: 13,
mis-server-1  |   details: 'Cluster ID : hpc01, Details : Error: 13 INTERNAL: convert memory error',
mis-server-1  |   metadata: Metadata {
mis-server-1  |     internalRepr: Map(3) {
mis-server-1  |       'is_scow_error' => [ '1' ],
mis-server-1  |       'scow_error_code' => [ 'CLUSTEROPS_ERROR' ],
mis-server-1  |       'clustererrors' => [
mis-server-1  |         '[{"clusterId":"hpc01","details":{"code":13,"details":"convert memory error","metadata":{"content-type":["application/grpc"],"grpc-status-details-bin":[{"type":"Buffer","data":[8,13,18,20,99,111,110,118,101,114,116,32,109,101,109,111,114,121,32,101,114,114,111,114,26,67,10,40,116,121,112,101,46,103,111,111,103,108,101,97,112,105,115,46,99,111,109,47,103,111,111,103,108,101,46,114,112,99,46,69,114,114,111,114,73,110,102,111,18,23,10,21,67,79,78,86,69,82,84,95,77,69,77,79,82,89,95,70,65,73,76,69,68]}]}}}]'
mis-server-1  |       ]
mis-server-1  |     },
mis-server-1  |     options: {}
mis-server-1  |   }
mis-server-1  | }
mis-server-1  |
mis-server-1  | Node.js v20.13.1
```

**Comment by liu-shaobo** [comment]
fix-memory分支的slurm-adapter已经修复
https://github.com/PKUHPC/scow-slurm-adapter/commit/0371344f5da7f5c3c5f30bc954e672dab7ec9979
<img width="863" alt="image" src="https://github.com/user-attachments/assets/d3c5a0a0-0ccb-453a-a9ac-95d1a0551d25">

**Comment by piccaSun** [comment]
上述修复已合并到适配器主分支 https://github.com/PKUHPC/scow-slurm-adapter
此问题已修复，关闭本Issue.
